[package]
name = "bindings_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiplayer_native = { path = "../" }
interoptopus = "0.13.15"
interoptopus_backend_csharp = "0.13.14"