name: Publish NuGet package and create GitHub release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore packages
        run: dotnet restore
      - name: Run tests
        run: dotnet test --verbosity normal
      - name: Package project
        run: dotnet pack -c Release
      - name: Publish package
        run: dotnet nuget push JKMP.Plugin.Multiplayer/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
      - name: Copy content files to temporary directory
        run: |
          mkdir -p out/dist/
          cp -R JKMP.Plugin.Multiplayer/bin/Release/net462/Content/ out/dist/
      - name: Package artifact
        uses: vimtor/action-zip@v1
        with:
          files: >
            JKMP.Plugin.Multiplayer/plugin.json
            JKMP.Plugin.Multiplayer/bin/Release/net462/JKMP.Plugin.Multiplayer.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/Resources.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/Matchmaking.Client.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/Multiplayer.Native.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/multiplayer_native.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/Myra.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/FontStashSharp.MonoGame.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/StbTrueTypeSharp.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/StbImageSharp.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/info.lundin.math.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/System.Memory.dll
            JKMP.Plugin.Multiplayer/bin/Release/net462/System.Runtime.CompilerServices.Unsafe.dll
            out/dist/
          dest: out/JKMP.Plugin.Multiplayer.zip
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: Modular release
          artifacts: "out/JKMP.Plugin.Multiplayer.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          generateReleaseNotes: true